server.port=8090

spring.datasource.url=jdbc:mysql://localhost:3307/nexuslogix_wms?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

nexuslogix.app.jwtSecret=NexusLogixWmsEnterpriseSecretForJwtSigningMustBeAtLeast256Bits2026
nexuslogix.app.jwtExpirationMs=86400000 